cluster: "sbatch --time={cluster.time} --mem={cluster.mem} --cpus-per-task={cluster.cpus} --qos={cluster.qos} {cluster.extra}"
jobs: 25
jobscript: "cluster/slurm_submit.sh"
cluster-config: "cluster/cluster_config.json"
cluster-cancel: scancel
jobname: "{rulename}_{jobid}"
latency-wait: 60

use-conda: True
rerun-incomplete: True
conda-frontend: "mamba"
printshellcmds: False